### ISSUE TITLE
Take a look at WWW::FreeProxyListsCom for inclusion

### ISSUE THREAD

**Issue by stevieb9** [olegwtf/proxyhunter#2]
[The module](https://metacpan.org/pod/WWW::FreeProxyListsCom) allows you to pull any/all of the proxy lists from http://www.freeproxylists.com in one fell swoop. It only returns a list, it does no checking, so it may be helpful for you here.

Disclaimer: I recently adopted the module.

**Comment by olegwtf** [comment]
I think this is a bad idea to include such specific proxy list extractor in proxyhunter itself. But if you are interested you can implement it as additional search engine for proxyhunter and publish it on cpan. See https://metacpan.org/pod/App::ProxyHunter::SearchEngine for details

**Comment by stevieb9** [comment]
Understood, and it makes sense. I'll take a look when I get some time.
